/**
 * Runtime copy planner for "Pull from Production".
 *
 * The pull tool used to carry a hand-maintained list of tables in FK-safe order.
 * It fell 35 tables behind the schema and needed three separate ordering
 * bugfixes along the way. This module derives the same information from the
 * live catalog (`sandbox_schema_graph()`), so a table added tomorrow is copied
 * without anyone remembering to add it.
 *
 * What the planner has to solve beyond a plain topological sort:
 *
 *  - Cycles. `rounds` ↔ `event_tee_times` and `events` ↔ `event_rules_versions`
 *    are mutually dependent. Break the cycle on a nullable edge: null the column
 *    on the first pass, then re-upsert the full rows afterwards to restore it.
 *  - Unreachable targets. `auth.users` lives outside the public schema and is
 *    never copied (staging auth users are created on demand by impersonation),
 *    so references into it must be nulled or remapped.
 *  - Denylisted targets. Skipping the derived fantasy pricing caches orphans
 *    `fantasy_picks.odds_snapshot_id` and friends; those are nullable, so the
 *    planner nulls them rather than dropping the picks.
 */

// ─── Schema graph, as returned by sandbox_schema_graph() ─────────────────────

export type SchemaGraph = {
  tables: Array<{ name: string; pk_columns: string[] }>;
  fk_edges: Array<{
    from_table: string;
    from_columns: string[];
    to_schema: string;
    to_table: string;
    constraint_name: string;
    nullable: boolean;
    is_self: boolean;
  }>;
  preserved: string[];
};

// ─── Tables that are wiped but never copied ──────────────────────────────────

export const DENY_COPY: Record<string, string> = {
  // Real users' Web Push endpoints. Staging must never be in a position to
  // deliver a test notification to somebody's actual phone.
  push_subscriptions:
    "real users' device endpoints — staging must not push to production phones",

  // Derived pricing caches. All are regenerated by the odds refresh, and
  // fantasy_joint_samples in particular holds gzipped Monte-Carlo matrices that
  // would dominate the in-memory snapshot.
  fantasy_odds_snapshots: "derived pricing cache — regenerated on odds refresh",
  fantasy_season_odds_snapshots: "derived pricing cache — regenerated on odds refresh",
  fantasy_score_pmfs: "derived pricing cache — regenerated on odds refresh",
  fantasy_joint_samples: "derived Monte-Carlo cache — large, regenerated on odds refresh",
  fantasy_cashout_offers: "derived cash-out prices — regenerated live",
  fantasy_season_cashout_offers: "derived cash-out prices — regenerated live",

  // A transient mutex, not data. Copying it would import a lock held by a
  // production request that finished long ago and block season imports.
  season_import_locks: "transient import lock — copying it would import a stale lock",
};

/**
 * NOT NULL references into unreachable schemas, with a runtime substitute.
 *
 * `group_charges.created_by` is `NOT NULL REFERENCES auth.users(id)` — the only
 * `created_by` in the schema that points at auth rather than `profiles`. It
 * cannot be nulled and its production value cannot exist in staging, so the
 * table has been failing on every pull. Remapping it to the operator running
 * the pull is the honest degradation: the charge rows arrive, attributed to
 * whoever pulled them.
 */
export const REMAP_TO_OPERATOR: Record<string, string[]> = {
  group_charges: ["created_by"],
};

// ─── Plan ────────────────────────────────────────────────────────────────────

export type CopyStep = {
  table: string;
  /** PK columns for the upsert conflict target; null when the table has no PK. */
  onConflict: string | null;
  /**
   * Columns nulled permanently, because their target is never copied. These
   * must stay null — restoring one would re-point at a row that isn't there.
   */
  nullColumns: string[];
  /**
   * Columns nulled only to break a foreign-key cycle. The real values are
   * restored by the fixup pass once every table is in place.
   */
  deferredColumns: string[];
  /** Columns replaced with the operator's auth uid. */
  operatorColumns: string[];
};

export type BlockedTable = { table: string; reason: string };

export type Fixup = {
  table: string;
  /** Columns that were nulled to break a cycle and must be restored. */
  columns: string[];
};

export type CopyPlan = {
  steps: CopyStep[];
  denied: BlockedTable[];
  blocked: BlockedTable[];
  fixups: Fixup[];
  discovered: number;
  preserved: string[];
  /** Should always be empty — a non-empty list means the planner has a hole. */
  uncovered: string[];
};

/**
 * Build a FK-safe copy order from the live schema graph.
 *
 * Ordering is alphabetical within each topological layer so that two runs
 * against the same schema produce byte-identical plans — worth having when the
 * output is the thing you read to diagnose a bad pull.
 */
export function planCopy(graph: SchemaGraph): CopyPlan {
  const preserved = new Set(graph.preserved ?? []);
  const allTables = graph.tables.map((t) => t.name);
  const pkByTable = new Map(graph.tables.map((t) => [t.name, t.pk_columns ?? []]));

  const denied: BlockedTable[] = [];
  const blocked: BlockedTable[] = [];

  const copyable = new Set<string>();
  for (const name of allTables) {
    if (preserved.has(name)) continue;
    if (name in DENY_COPY) {
      denied.push({ table: name, reason: DENY_COPY[name] });
      continue;
    }
    copyable.add(name);
  }

  // Columns to null / remap, accumulated as we classify edges. `nullColumns`
  // are permanent; `deferredColumns` are restored by the fixup pass.
  const nullColumns = new Map<string, Set<string>>();
  const deferredColumns = new Map<string, Set<string>>();
  const operatorColumns = new Map<string, Set<string>>();
  const addTo = (m: Map<string, Set<string>>, table: string, cols: string[]) => {
    const set = m.get(table) ?? new Set<string>();
    cols.forEach((c) => set.add(c));
    m.set(table, set);
  };

  // Resolve references into tables that are never copied — another schema
  // (auth.users), denylisted, or preserved. Nullable references are dropped to
  // NULL so the child rows still arrive; a NOT NULL reference makes the child
  // table undeliverable, which can in turn strand its own children. Iterate to
  // a fixpoint so that cascade is followed all the way down.
  const edges = graph.fk_edges.filter((e) => !e.is_self);
  let changed = true;
  while (changed) {
    changed = false;
    for (const edge of edges) {
      if (!copyable.has(edge.from_table)) continue;
      if (edge.to_schema === "public" && copyable.has(edge.to_table)) continue;

      const remappable = REMAP_TO_OPERATOR[edge.from_table];
      if (remappable && edge.from_columns.every((c) => remappable.includes(c))) {
        addTo(operatorColumns, edge.from_table, edge.from_columns);
      } else if (edge.nullable) {
        addTo(nullColumns, edge.from_table, edge.from_columns);
      } else {
        blocked.push({
          table: edge.from_table,
          reason: `${edge.from_columns.join(", ")} is NOT NULL and references ${edge.to_schema}.${edge.to_table}, which is never copied`,
        });
        copyable.delete(edge.from_table);
        changed = true;
      }
    }
  }

  // Dependency edges between the tables that survived: from → (to → edges).
  const deps = new Map<string, Map<string, SchemaGraph["fk_edges"]>>();
  for (const t of copyable) deps.set(t, new Map());

  for (const edge of edges) {
    if (!copyable.has(edge.from_table) || !copyable.has(edge.to_table)) continue;
    if (edge.to_schema !== "public") continue;
    const byTarget = deps.get(edge.from_table)!;
    byTarget.set(edge.to_table, [...(byTarget.get(edge.to_table) ?? []), edge]);
  }

  // ─── Topological sort (Kahn), breaking cycles on nullable edges ────────────

  const fixups: Fixup[] = [];
  const emitted: string[] = [];
  const remaining = new Set(copyable);

  const ready = () =>
    [...remaining].filter((t) => (deps.get(t)?.size ?? 0) === 0).sort();

  while (remaining.size > 0) {
    let batch = ready();

    if (batch.length === 0) {
      // Cycle. Break the alphabetically-first dependency whose every edge is
      // nullable: null those columns now, restore them in the fixup pass.
      const broken = breakOneCycleEdge(remaining, deps);
      if (!broken) {
        // No nullable edge anywhere in the cycle — unorderable. Report the
        // whole remaining set rather than looping forever.
        for (const t of [...remaining].sort()) {
          blocked.push({
            table: t,
            reason: "part of a foreign-key cycle with no nullable edge to break",
          });
          remaining.delete(t);
        }
        break;
      }
      addTo(deferredColumns, broken.from, broken.columns);
      fixups.push({ table: broken.from, columns: broken.columns });
      batch = ready();
      if (batch.length === 0) continue;
    }

    for (const table of batch) {
      emitted.push(table);
      remaining.delete(table);
      for (const [, byTarget] of deps) byTarget.delete(table);
      deps.delete(table);
    }
  }

  const steps: CopyStep[] = emitted.map((table) => {
    const pk = pkByTable.get(table) ?? [];
    return {
      table,
      onConflict: pk.length > 0 ? pk.join(",") : null,
      nullColumns: [...(nullColumns.get(table) ?? [])].sort(),
      deferredColumns: [...(deferredColumns.get(table) ?? [])].sort(),
      operatorColumns: [...(operatorColumns.get(table) ?? [])].sort(),
    };
  });

  const accounted = new Set<string>([
    ...emitted,
    ...denied.map((d) => d.table),
    ...blocked.map((b) => b.table),
    ...preserved,
  ]);
  const uncovered = allTables.filter((t) => !accounted.has(t)).sort();

  return {
    steps,
    denied,
    blocked,
    fixups,
    discovered: allTables.length,
    preserved: [...preserved].sort(),
    uncovered,
  };
}

/**
 * Find one dependency in the remaining subgraph that can be severed by nulling
 * its columns, and sever it. Deterministic: alphabetical by source then target.
 */
function breakOneCycleEdge(
  remaining: Set<string>,
  deps: Map<string, Map<string, SchemaGraph["fk_edges"]>>
): { from: string; columns: string[] } | null {
  for (const from of [...remaining].sort()) {
    const byTarget = deps.get(from);
    if (!byTarget) continue;
    for (const to of [...byTarget.keys()].sort()) {
      const edges = byTarget.get(to)!;
      if (edges.length === 0 || !edges.every((e) => e.nullable)) continue;
      byTarget.delete(to);
      return { from, columns: [...new Set(edges.flatMap((e) => e.from_columns))].sort() };
    }
  }
  return null;
}

/**
 * Apply a step's null / operator-remap rules to a production row.
 *
 * `phase` picks which nulls apply. On the first pass both the permanent nulls
 * and the cycle-broken columns are cleared; on the fixup pass only the
 * permanent ones are, so the cycle columns come back with their real values
 * while references into never-copied tables stay null.
 */
export function applyStepTransform(
  step: Pick<CopyStep, "nullColumns" | "deferredColumns" | "operatorColumns">,
  row: Record<string, unknown>,
  operatorAuthUid: string,
  phase: "initial" | "fixup" = "initial"
): Record<string, unknown> {
  const toNull =
    phase === "fixup" ? step.nullColumns : [...step.nullColumns, ...step.deferredColumns];
  if (toNull.length === 0 && step.operatorColumns.length === 0) return row;
  const next = { ...row };
  for (const col of toNull) next[col] = null;
  for (const col of step.operatorColumns) next[col] = operatorAuthUid;
  return next;
}
